/**
 * Indicates where order creation was initialized
 * Used for subsequent analysis
 */
export enum EnumOrderSource {
    /**
     * The button is placed on the website. A payment link is generated after certain user actions (clicking the button) on the website
     */
    Website = 'WEBSITE',
    /**
     * The button is placed in the mobile app. A payment link is generated after certain user actions (tapping the button) in the app
     */
    App = 'APP',
    /**
     * A payment link is generated by a manager in the CRM system or another admin panel
     */
    Crm = 'CRM',
    /**
     * A payment link is generated to be displayed in the offline cash register
     */
    CashRegister = 'CASH_REGISTER',
    /**
     * The payment link is generated in the CMS plugin.
     */
    CmsPlugin = 'CMS_PLUGIN'
}
